# Generated by Django 5.2.1 on 2025-05-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_compra',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_en_stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
