# Generated by Django 5.2.1 on 2025-05-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
