# Generated by Django 5.2.1 on 2025-05-26 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_categoriaproducto_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialprecio',
            name='rol',
            field=models.CharField(blank=True, help_text='Rol del usuario que hizo el cambio', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historialprecio',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que modificó el precio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='rol',
            field=models.CharField(blank=True, help_text='Rol del usuario que hizo el movimiento', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
