# Generated by Django 5.2.1 on 2025-05-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_historialprecio_rol_historialprecio_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='serial_number',
            field=models.CharField(blank=True, editable=False, help_text='Número de serie generado automáticamente', max_length=20, unique=True),
        ),
    ]
